### ISSUE TITLE
What did I do wrong?

### ISSUE THREAD

**Issue by Tankieboy** [maca88/BikeLightsControl#1] opened 2021-01-09 12:59 UTC
![20210109_123647](https://user-images.githubusercontent.com/47142372/104092191-3692a500-527a-11eb-8b5a-a5ee09d3b66c.jpg)

Edge 530. I thought I followed all the steps

**Comment by maca88** [comment] 2021-01-09 13:39
Hi, thanks for reporting the issue. The error is very strange as it throws when retrieving a setting:
```
Devices:
    EdgeÂ® 530: 7.00
App Versions: 0.5.2
Backtrace:
    BikeLightsView.onNetworkStateUpdate:336
    BikeLightsControlView.onNetworkStateUpdate:173
    BikeLightsView.onLightNetworkStateUpdate:17
```

I will remove the settings as it is not used anyways for this widget and release a new version.
Why did you close the issue?

**Comment by Tankieboy** [comment] 2021-01-09 14:44
Thank you. No idea, I got click excited!

Also as I can download code from github as a zip, is there a way to sideload into an edge 530?

**Comment by maca88** [comment] 2021-01-09 15:00
Yes there is, you need to the the following steps:
- First to [install Connect IQ SDK](https://developer.garmin.com/connect-iq/connect-iq-basics/getting-started/)
- Change the `id` attribute in the manifest.xml file in the Source folder to a different uuid (e.g.: c46df1bd852444c694e7b86544f46d48)
- Compile the code by using Eclipse
- Copy the BikeLightsControl.prg from the bin folder to your Edge folder: X:\Garmin\Apps
- Start your Garmin and the compiled widget should be installed

Optional step: In order to print logs with `System.println` in a file you need to create in your Garmin device an empty file named BikeLightsControl.TXT inside folder: X:\Garmin\Apps\LOGS

**Comment by maca88** [comment] 2021-01-09 15:05
I updated the previous comment by adding another step for changing the `id` attribute in order to avoid collision with the widget from the Garmin store.

**Comment by maca88** [comment] 2021-01-09 15:12
I did check the zip download and it turns out that the submodule is not included. This means that you need to download also the zip from https://github.com/maca88/SmartBikeLights and extract it in the `BikeLightsControl-master\Source\SmartBikeLights` folder. This repository uses the code from `SmartBikeLights` which is a data field.

**Comment by maca88** [comment] 2021-01-09 19:36
I released a new version (0.5.3) that should fix the reported error, can you please try it and report whether the problem is fixed?

**Comment by Tankieboy** [comment] 2021-01-10 18:24
Working fine, thanks

**Comment by maca88** [comment] 2021-01-10 19:50
Thanks for letting me know, closing the issue.

**Closed as completed by maca88** 2021-01-10 19:50 UTC
